### ISSUE TITLE
Test the bxt docker production:latest

### ISSUE THREAD

**Issue by fhdk** [anydistro/bxt#127]
Starting a sync turns into a loop

I have it running in a seperate window so I can follow the bxt downloading log.

I became suspicious of a loop when the aarch repo started downloading again and I kept watching and now the x86_64 repo is downloading again.

The folder `/var/lib/docker` is steadily increasing in sized at the time I post this the size and steadily increasing

```
11:32:11 ○ [fh@tiger] ~
 $ sudo du -b -c -h /var/lib/docker

[....]

266G    /var/lib/docker
266G    total

11:32:26 ○ [fh@tiger] ~
```

**Comment by fhdk** [comment]
Followup - it seems the container is a really weird state

    docker container stats bxt-production-1

![image](https://github.com/user-attachments/assets/dc26e58f-480f-4cb1-919e-8c3a63c31049)

**Comment by fhdk** [comment]
Giving the docker instance time to exit gracefully

    docker stop -t 300 $(docker ps -q)

After 5 minutes it is killed.

Starting the instance again - there is no files in the repo - so restart sync.

```
13:23:39 ± [fh@tiger] .../manjaro-bxt/bxt
[master] $ docker compose up &
[1] 310016

13:26:30 ± [fh@tiger] .../manjaro-bxt/bxt
[+] Running 2/0
 ✔ Container bxt-production-1   Created                                                                                         0.0s 
 ✔ Container bxt-development-1  Created                                                                                         0.0s 
Attaching to development-1, production-1
production-1   | [2024-07-26 11:26:30.415281][debug]: Pool: Counted links for 0 paths
development-1 exited with code 0
production-1   | [2024-07-26 11:27:03.954365][trace]: Sync started by 

[....]
```
This time I am watching the instance

    docker container stats bxt-production-1

The MEM USAGE starts around 1G, then it is slowly increasing while the daemon locates which packages is in cache.

![image](https://github.com/user-attachments/assets/9cca70b8-62f4-4df3-8a7d-bd148f30c48d)

After ~13m the memory consumption has increased to 14.5G and increasing.

**Comment by fhdk** [comment]
Testing with setting a limit in the compose file - see how this pan out

```
services:
  development:
    image: bxt_development:latest
    build:
      context: .
      target: development
    ports:
      - "8080:8080"
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

  production:
    image: bxt_production:latest
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
    build:
      context: .
      target: production
    ports:
      - "80:8080"
    volumes:
      - persistence_volume:/app/persistence/

volumes:
  persistence_volume:
```
